### ISSUE TITLE
NativeOssFileSystem.listStatus return null

### ISSUE THREAD

**Issue by luoli523** [aliyun/aliyun-spark-sdk#18]
NativeOssFileSystem.listStatus should not return null if the directory on OSS has nothing in it(files or directories). Otherwise, it will case NPE in many place.

Make sure it return a empty FileStatus[] please

![image](https://cloud.githubusercontent.com/assets/525390/9927116/5aef9344-5d4e-11e5-98cb-542464d1b9d5.png)

**Comment by uncleGen** [comment]
@luoli523  LGTM
