### ISSUE TITLE
readme中提到的ossn和官网说明的差异问题。

### ISSUE THREAD

**Issue by shengnoah** [aliyun/aliyun-spark-sdk#41]
官网只提到了oss和ossref。
github上的oss和ossn中的ossn还有效吗？

**Comment by uncleGen** [comment]
@shengnoah，这个地方确实会产生一些混淆。
1. ossref协议在EMR中配置作业时会用到，在应用参数框中引用作业需要用到的资源文件。例如作业Jar包或者其他第三方Jar包等。作用也仅此而已。
2. 原ossn协议已经更名了，不再使用。github文档有些过时。
3. 原ossn协议更名为oss，原oss协议更名为ossbfs。
4. 代码中读写OSS文件只能使用oss协议和ossbfs协议。
5. ossbfs是基于块划分的文件，和原生OSS文件有些区别。这两种文件存在与一个bucket中时造成异常发生。所以建议你一个bucket中只使用一种格式文件。

**Comment by shengnoah** [comment]
@uncleGen  多谢您的回答！
