### ISSUE TITLE
官网中的一项conf.set与github例子不一样。

### ISSUE THREAD

**Issue by shengnoah** [aliyun/aliyun-spark-sdk#43]
在官网上conf的set有一项，如下：

conf.set("spark.hadoop.fs.oss.impl", "com.aliyun.fs.oss.nat.NativeOssFileSystem")

在github的readme里这一句已经去掉了，这句设置请问是否还延续有效？

**Comment by uncleGen** [comment]
@shengnoah 有效。
README中已经更新过了，官网文档和这里的是一致的。

**Comment by shengnoah** [comment]
http://help.aliyun.com/document_detail/emr/best-practice/Spark.html

就是这个链接里面：

快速入门

Spark接入OSS

下面这个例子演示了Spark如何从OSS中读入数据，并处理完写回到OSS中。

    val conf = new SparkConf().setAppName("Test OSS")
    conf.set("spark.hadoop.fs.oss.accessKeyId", "accessKeyId")
    conf.set("spark.hadoop.fs.oss.accessKeySecret", "accessKeySecret")
    conf.set("spark.hadoop.fs.oss.endpoint", "endpoint")
    conf.set("spark.hadoop.fs.oss.impl", "com.aliyun.fs.oss.nat.NativeOssFileSystem")
    val sc = new SparkContext(conf)

    val pathIn = "oss://bucket/path/to/read"
    val inputData = sc.textFile(pathIn)
    val cnt = inputData.count
    println(s"count: $cnt")

    val outputPath = "oss://bucket/path/to/write"
    val outpuData = inputData.map(e => s"$e has been processed.")
    outpuData.saveAsTextFile(outputPath)



还有一个下面的例子文件：

package com.aliyun.amr.examples

import org.apache.spark.aliyun.oss.OssOps
import org.apache.spark.{SparkConf, SparkContext}

object OssSample {

  def main(args: Array[String]): Unit = {

    val accessKeyId = args(0)
    val accessKeySecret = args(1)
	val endpoint = args(2)
    val inPath = args(3)
    val outPath = args(4)
    val numPartition = 2    

    val conf = new SparkConf().setAppName("OssSample")
    conf.set("spark.hadoop.fs.oss.accessKeyId", accessKeyId)
    conf.set("spark.hadoop.fs.oss.accessKeySecret", accessKeySecret)
    conf.set("spark.hadoop.fs.oss.endpoint", endpoint)
	
    val sc = new SparkContext(conf)
    val ossOps = OssOps(sc, endpoint, accessKeyId, accessKeySecret)

    val inputData = ossOps.readOssFile(inPath, numPartition)
    inputData.top(2).foreach(println(_))
    val resultData = inputData.map(e => s"reading $e")
    ossOps.saveToOssFile(outPath, resultData)
  }
}

conf.set("spark.hadoop.fs.oss.impl", "com.aliyun.fs.oss.nat.NativeOssFileSystem")
请问这句set或不set的区别。



有时候还会抛出这种异常。
Exception in thread "main" java.io.IOException: No FileSystem for scheme: oss

**Comment by shengnoah** [comment]
是下载 
http://docs-aliyun.cn-hangzhou.oss.aliyun-inc.com/cn/emr/0.0.6/assets/lib/emr-sdk_2.10-0.1.0.jar?Expires=1448513000&OSSAccessKeyId=80kJOHQaA4syuazx&Signature=XvdtXT925cjGL21hAXGWkr6iYp8%3D 


请问是这个链接的.jar运行比较新。
还是编译github上的最新的代码比较新？

**Comment by shengnoah** [comment]
http://aligitlab.oss-cn-hangzhou-zmf.aliyuncs.com/uploads/aliyundocumentcenteredit/amr/99091fefb1/1.JPG

这个作业配置实例的图片，貌似始终看不到图片。

**Comment by shengnoah** [comment]
val accessKeyId = ""
                val accessKeySecret = ""

                // hangzhou for example
                val endpoint = "http://oss-cn-beijing.aliyuncs.com"

                val conf = new SparkConf().setAppName("TEST")
                conf.set("spark.hadoop.fs.oss.accessKeyId", accessKeyId)
                conf.set("spark.hadoop.fs.oss.accessKeySecret", accessKeySecret)
                conf.set("spark.hadoop.fs.oss.endpoint", endpoint)
                conf.set("spark.hadoop.fs.oss.impl", "com.aliyun.fs.oss.nat.NativeOssFileSystem")
                //conf.set("spark.hadoop.fs.oss.impl", "com.aliyun.fs.oss.blk.OssFileSystem")

                val sc = new SparkContext(conf)
                val ossOps = OssOps(sc, endpoint, accessKeyId, accessKeySecret)

                val inputPath =  "oss://xxx-dns/20201010"
                val inputData = sc.textFile(inputPath)

我们用的测试代码是这样的。

**Comment by uncleGen** [comment]
@shengnoah 
1. github永远保持最新。
2. set的目的是对使用oss协议头的路径使用NativeOssFileSystem实现来读写OSS数据
     具体报错的场景是？
3.  图片在我这里是正常的。

**Comment by uncleGen** [comment]
@shengnoah Jar包把sdk也打进去试试

**Comment by uncleGen** [comment]
@shengnoah 图片确实有些问题，稍等。

**Comment by shengnoah** [comment]
主要就是做一下测试，分别建立sbt，mvn的工程访问oss文件。


package com.spark.demo

import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.SparkConf
import org.apache.spark.aliyun.oss.OssOps

object App {

  def main(args : Array[String]) {
                val accessKeyId = ""
                val accessKeySecret = ""

                // hangzhou for example
                val endpoint = "http://oss-cn-beijing.aliyuncs.com"

                val conf = new SparkConf().setAppName("Test OSS")
                conf.set("spark.hadoop.fs.oss.accessKeyId", accessKeyId)
                conf.set("spark.hadoop.fs.oss.accessKeySecret", accessKeySecret)
                conf.set("spark.hadoop.fs.oss.endpoint", endpoint)
                conf.set("spark.hadoop.fs.oss.impl", "com.aliyun.fs.oss.nat.NativeOssFileSystem")

                val sc = new SparkContext(conf)

                val ossOps = OssOps(sc, endpoint, accessKeyId, accessKeySecret)
                val inputPath =  "oss://xxx-dns/20201010"
                val inputData = sc.textFile(inputPath)
                val counts = inputData.flatMap(line => line.split(" "))
                                .map(word => (word, 1))

                println("##########################################################")
                print(inputData.count)
                println(inputData)
                println(counts)
                println("##########################################################")
  }
}

没有复杂逻辑，就是测试代码。

现在这个是mvn工程，已经编译了github上最新的包。
mvn安装到本机。

spark-submit --class com.spark.demo.App  --executor-memory 2G  --total-executor-cores 4   --driver-class-path  lib/emr-sdk_2.10-1.0.0.jar target/spark-hello-1.0-SNAPSHOT.jar

编译和提交任务的时候都指定lib jar的位置。pom里也加入了依赖。

**Comment by shengnoah** [comment]
.
./target
./target/classes.timestamp
./target/classes
./target/classes/com
./target/classes/com/spark
./target/classes/com/spark/demo
./target/classes/com/spark/demo/App$.class
./target/classes/com/spark/demo/App$$anonfun$1.class
./target/classes/com/spark/demo/App.class
./target/classes/com/spark/demo/App$$anonfun$2.class
./target/test-classes
./target/spark-hello-1.0-SNAPSHOT.jar
./target/surefire
./target/maven-archiver
./target/maven-archiver/pom.properties
./src
./src/main
./src/main/scala
./src/main/scala/com
./src/main/scala/com/spark
./src/main/scala/com/spark/demo
./src/main/scala/com/spark/demo/App.scala
./lib
./lib/emr-sdk_2.10-1.0.0.jar
./pom.xml



    <dependency>
      <groupId>com.aliyun</groupId>
      <artifactId>emr-sdk_2.10</artifactId>
      <version>1.0.0</version>
    </dependency>

**Comment by uncleGen** [comment]
@shengnoah 测试代码没什么问题。如果只是driver的cp包括sdk，executor上还是会报错的。你可以直接将sdk打进作业Jar包中。具体的例子你可以看工程中的examples模块pom。或者你直接用工程打出来的examples jar包试试。

**Comment by uncleGen** [comment]
@shengnoah 现在有什么问题吗？

**Comment by shengnoah** [comment]
@uncleGen   暂时没什么问题了，如果代码以github为准，之后就直接关注github了，多谢你的方法，我们再测试一下！

希望github的readme.md
“Step-1. Initialize an OssOps”
里加上那句
conf.set("spark.hadoop.fs.oss.impl", "com.aliyun.fs.oss.nat.NativeOssFileSystem")
怕之后的同学，也会踩上坑。

如果图片能显示出来就更好了。

多谢！

**Comment by shengnoah** [comment]
Native URI： oss://[accesskeyId:accessKeySecret@]bucket/object/path
Block-based URI: ossbfs://[accesskeyId:accessKeySecret@]bucket/object/path

这个[accesskeyId:accessKeySecret@] 需要体现到代码，还是像以前一样。

val inputPath =  "oss://xxx-dns/20201010"
设置里吗？

**Comment by uncleGen** [comment]
@shengnoah, oss://[accesskeyId:accessKeySecret@]bucket/object/path，你可以写： 
1. 
        conf.set("spark.hadoop.fs.oss.accessKeyId", accessKeyId)
        conf.set("spark.hadoop.fs.oss.accessKeySecret", accessKeySecret)
        ......
        val inputPath = "oss://xxx-dns/20201010"

2.  val inputPath = "oss://accesskeyId:accesskeySecret@xxx-dns/20201010"

URI的格式还会有些变化，后面会在release note中提醒。

**Comment by shengnoah** [comment]
@shengnoah 收到！
