### ISSUE TITLE
example例子的运行

### ISSUE THREAD

**Issue by shengnoah** [aliyun/aliyun-spark-sdk#45]
spark-submit --class com.aliyun.emr.examples.TestOss  --executor-memory 2G  --total-executor-cores 4   --driver-class-path  lib/emr-sdk_2.10-1.0.0.jar target/emr-examples_2.10-1.0.0.jar

已经把example TestOss类中，从args取得的参数， 

    val accessKeyId =""
    val accessKeySecret = ""
    val endpoint = "http://oss-cn-beijing.aliyuncs.com"
    val inputPath = "oss://xxxlab-dns/20201010"
    val numPartitions = 2

全部写成了固定值。

        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>emr-sdk_2.10</artifactId>
            <version>1.0.0</version>
        </dependency>

新版本的git代码默认就有。

The top 10 lines are:
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.aliyun.fs.oss.nat.NativeOssFileSystem not found

请问能不能，不把sdk的源码和客户端调用放到一起，成为独立依赖的jar去执行oss的访问？

**Comment by uncleGen** [comment]
@shengnoah 可以，你打包时只要将sdk的jar打进去。

**Comment by shengnoah** [comment]
有一个想法，就是的例子，如果能统一

用这种：
      val conf = new SparkConf().setAppName("Test OSS")
      conf.set("spark.hadoop.fs.oss.accessKeyId", accessKeyId)
      conf.set("spark.hadoop.fs.oss.accessKeySecret", accessKeySecret)
      conf.set("spark.hadoop.fs.oss.endpoint", endpoint)
      conf.set("spark.hadoop.fs.oss.impl", "com.aliyun.fs.oss.nat.NativeOssFileSystem")


或者统一下：

val ossData = OssOps(sc, endpoint, accessKeyId, accessKeySecret).readOssFile(inputPath, numPartitions)



因为readme.md说明里用了conf.set,有的项目set了，有的没有set。或是多一个少一个。

像example里TestOss的代码，就一个conf.set 也没有。

其实意思都能明白，有时候被绕进去了。


多谢解答！
如果不能独立，把SDK放进去也可以。

**Comment by uncleGen** [comment]
@shengnoah 第一种可以直接用spark提供的sc.textFile(...)，可能更好接受些。提供OssOps实际上和其他例如ODPS等接口保持一种统一风格。对于OSS来说这两种都可以，看你个人的选择。

**Comment by shengnoah** [comment]
@uncleGen  收到，多谢！
